matrix:
  user_id: "@testbot123:matrix.org"
  user_password: "testbot123"
  homeserver_url: "https://matrix.org"

database:
  name: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
