matrix:
  user_id: "<full user matrix id>"
  user_password: "<user password>"
  homeserver_url: "https://matrix.org"

database:
  name: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
